package vistas;

import veterinaria.expertos.ExpertoAdministrarCliente;
import veterinaria.expertos.ExpertoAdministrarVeterinaria;

/**
 *
 * @author mauri
 */
public class EliminarCliente extends javax.swing.JFrame {

    
    private ExpertoAdministrarVeterinaria expertoVeterinaria;
    
    public EliminarCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpEliminarCliente = new javax.swing.JPanel();
        jlEliminarCliente = new javax.swing.JLabel();
        jlEliminarClienteYDatos = new javax.swing.JLabel();
        jbSi = new javax.swing.JButton();
        jbNo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpEliminarCliente.setBackground(new java.awt.Color(153, 204, 255));
        jpEliminarCliente.setMaximumSize(new java.awt.Dimension(800, 600));
        jpEliminarCliente.setMinimumSize(new java.awt.Dimension(800, 600));
        jpEliminarCliente.setPreferredSize(new java.awt.Dimension(800, 600));

        jlEliminarCliente.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jlEliminarCliente.setText("-ELIMINAR CLIENTE-");

        jlEliminarClienteYDatos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlEliminarClienteYDatos.setText("¿Esta seguro que desea eliminar el cliente y sus datos, incluyendo ");

        jbSi.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jbSi.setText("Si");
        jbSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSiActionPerformed(evt);
            }
        });

        jbNo.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jbNo.setText("No");
        jbNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNoActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/images/usuario.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("sus mascotas asociadas?");

        javax.swing.GroupLayout jpEliminarClienteLayout = new javax.swing.GroupLayout(jpEliminarCliente);
        jpEliminarCliente.setLayout(jpEliminarClienteLayout);
        jpEliminarClienteLayout.setHorizontalGroup(
            jpEliminarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEliminarClienteLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(jpEliminarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlEliminarClienteYDatos)
                    .addGroup(jpEliminarClienteLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(63, 63, 63)
                        .addComponent(jlEliminarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpEliminarClienteLayout.createSequentialGroup()
                .addGroup(jpEliminarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpEliminarClienteLayout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jbSi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(jbNo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpEliminarClienteLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addGap(267, 267, 267))
        );
        jpEliminarClienteLayout.setVerticalGroup(
            jpEliminarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEliminarClienteLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jpEliminarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpEliminarClienteLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jlEliminarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(119, 119, 119)
                .addComponent(jlEliminarClienteYDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addGroup(jpEliminarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(123, 123, 123))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpEliminarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpEliminarCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSiActionPerformed
        expertoVeterinaria.borrarCliente();
        VeterinariaMenuPrincipal veterinariaMenuPrincipal = new VeterinariaMenuPrincipal();
        veterinariaMenuPrincipal.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jbSiActionPerformed

    private void jbNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNoActionPerformed
        AdministradorCliente administradorCliente = new AdministradorCliente();
        administradorCliente.setExpertoVeterinaria(expertoVeterinaria);
        administradorCliente.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jbNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarCliente().setVisible(true);
            }
        });
    }

    

    public void setExpertoVeterinaria(ExpertoAdministrarVeterinaria expertoVeterinaria) {
        this.expertoVeterinaria = expertoVeterinaria;
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbNo;
    private javax.swing.JButton jbSi;
    private javax.swing.JLabel jlEliminarCliente;
    private javax.swing.JLabel jlEliminarClienteYDatos;
    private javax.swing.JPanel jpEliminarCliente;
    // End of variables declaration//GEN-END:variables
}
